name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "my first github actons job"
        
        - name: list file
          run: ls

        - name: read file
          run: cat README.md
        