name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: list and read file
          run: |
            echo "my first github actons job"
            ls -ltra
            cat README.md
        - name: generate ascii artwork 
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

  
        